name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security_tests:
    name: Unit Tests + SonarQube + Docker + OWASP ZAP
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install Python Dependencies
      - name: Install Dependencies
        run: |
          pip install coverage fastapi uvicorn requests

      # Step 4: Run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          coverage run -m unittest discover -s src -p "test_*.py"
          coverage xml

      # Step 5: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=Gayathri17sk_dev_sec
            -Dsonar.organization=gayathri17sk
            -Dsonar.sources=src
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Step 7: Run Docker Container (FastAPI)
      - name: Run Docker Container
        run: |
          docker run -d --name myapp_container -p 8000:8000 myapp:latest
          # Wait until FastAPI is ready
          for i in {1..40}; do
            curl -s http://localhost:8000/health && break
            echo "Waiting for app to start..."
            sleep 3
          done

      # Step 8: OWASP ZAP Full Scan using GitHub Action
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "http://localhost:8000/"
          token: ${{ github.token }}
          artifact_name: "zap_full_scan"
          fail_action: true

      # Step 9: Stop Docker Container
      - name: Stop Container
        run: |
          docker stop myapp_container
          docker rm myapp_container
