name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security_tests:
    name: Unit Tests + SonarQube + Docker + OWASP ZAP
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install coverage

      # Step 4: Run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          coverage run -m unittest discover -s src -p "test_*.py"
          coverage xml

      # Step 5: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=Gayathri17sk_dev_sec
            -Dsonar.organization=gayathri17sk
            -Dsonar.sources=src
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 8: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Step 9: Run Docker Container (Expose Port 8000)
      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name myapp_container myapp:latest
          sleep 10

      # Step 10: OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        run: |
          docker pull zaproxy/zap-stable
          docker run \
            -v $(pwd):/zap/wrk \
            --network="host" \
            zaproxy/zap-stable zap-baseline.py \
            -t http://localhost:8000 \
            -r zap_report.html

      # Step 11: Upload OWASP ZAP Report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_report.html

      # Step 12: Stop Container
      - name: Stop Container
        run: |
          docker stop myapp_container
          docker rm myapp_container
